name: Continuous Integration

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install build toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-multilib clang clang-tidy make

      - name: Build project
        run: make

      - name: Run clang-tidy
        run: |
          git ls-files '*.c' | xargs -n 1 clang-tidy -- -I.
